import { describe, it, expect } from 'vitest';
import {
  loadMethods,
  loadStage,
  classesForStage,
  stagesForClass,
  isAvailable,
  CCCBR_FILE_CLASSES,
  CCCBR_AVAILABILITY,
  CccbrLoadError,
  DEFAULT_BASE_URL,
  type FetchLike,
} from '../cccbr/index.js';
import { Stage } from '../bell.js';
import { Method } from '../method.js';

// ---------------------------------------------------------------------------
// Fixtures — minimal but genuine CCCBR Text rows. The parser itself is covered
// by parse-cccbr-text.test.ts; here we exercise the *loader* (URLs, provenance,
// merging, error handling) with an injected fake fetch — no network.
// ---------------------------------------------------------------------------

const GENERATED_LINE =
  'Copyright (c) 2026 Central Council. Generated by Composition Library on Mon 06 Jul 2026 17:49:53';

function file(rows: string[][]): string {
  const header =
    'Id\tMethod\tFirst rung\tRefs\tFCHs\tStage\tSym\tLit\tLLen\tLeadhead\tPlace Notation';
  return [
    'Central Council Collection of Methods',
    GENERATED_LINE,
    'Some Heading',
    '',
    header,
    ...rows.map((r) => r.join('\t')),
  ].join('\n');
}

/** A row with a coded lead head; `tokens` become the place notation. */
function row(id: string, name: string, stage: number, code: string, tokens: string[]): string[] {
  return [id, name, '', '', '', String(stage), 'P', '', '24', code, ...tokens];
}

// A real-ish Minor place notation (parses to a valid Method regardless of class label).
const CAMBRIDGE_MINOR = row('16123', 'Cambridge', 6, 'k',
  ['-', '36', '-', '14', '-', '12', '-', '36', '-', '14', '-', '56']);
const IPSWICH_MINOR = row('16130', 'Ipswich', 6, 'k',
  ['-', '36', '-', '14', '-', '12', '-', '36', '-', '34', '-', '16']);

/** A fake fetch backed by an in-memory URL->body map; records the URLs it was asked for. */
function fakeFetch(bodies: Record<string, string>) {
  const calls: string[] = [];
  const fn: FetchLike = async (url) => {
    calls.push(url);
    const body = bodies[url];
    if (body === undefined) return { ok: false, status: 404, text: async () => 'Not found' };
    return { ok: true, status: 200, text: async () => body };
  };
  return { fn, calls };
}

const BASE = 'https://test.example/text';

describe('cccbr-methods — availability map', () => {
  it('lists the eight fetchable file classes (not the classification enum)', () => {
    expect(CCCBR_FILE_CLASSES).toContain('Surprise');
    expect(CCCBR_FILE_CLASSES).toContain('Treble Bob');
    expect(CCCBR_FILE_CLASSES).toHaveLength(8);
    // "Bob"/"Place"/"Principle" are classifications, not file classes.
    expect(CCCBR_FILE_CLASSES).not.toContain('Bob' as never);
  });

  it('knows which stages a class publishes', () => {
    expect(stagesForClass('Surprise')).toContain(6);
    expect(stagesForClass('Surprise')).not.toContain(7); // no Surprise Triples
    expect(CCCBR_AVAILABILITY['Surprise']).toEqual(stagesForClass('Surprise'));
  });

  it('knows which classes publish a stage', () => {
    // Only Plain and Surprise go up to Twenty.
    expect(classesForStage(20).sort()).toEqual(['Plain', 'Surprise']);
    expect(isAvailable('Surprise', 6)).toBe(true);
    expect(isAvailable('Surprise', 7)).toBe(false);
  });

  it('defaults to the CCCBR HTTPS endpoint', () => {
    expect(DEFAULT_BASE_URL).toBe('https://methods.cccbr.org.uk/text');
  });
});

describe('cccbr-methods — loadMethods', () => {
  it('fetches exactly one file for one (class, stage) and parses it', async () => {
    const url = `${BASE}/CCCBR_Surprise6.html`;
    const { fn, calls } = fakeFetch({ [url]: file([CAMBRIDGE_MINOR, IPSWICH_MINOR]) });

    const { library, provenance } = await loadMethods('Surprise', Stage.MINOR, { fetch: fn, baseUrl: BASE });

    expect(calls).toEqual([url]); // one file, no over-fetching
    expect(library.size).toBe(2);
    expect(library.find('Cambridge Surprise Minor')).toMatchObject({
      id: 16123, stage: 6, classification: 'Surprise', leadHeadCode: 'k',
    });
    // The returned library is a real, usable MethodLibrary.
    const m = library.method('Cambridge Surprise Minor');
    expect(m).toBeInstanceOf(Method);

    expect(provenance).toMatchObject({
      source: 'cccbr-text',
      upstreamGenerated: 'Mon 06 Jul 2026 17:49:53',
      stages: [6],
      fileClasses: ['Surprise'],
      methodCount: 2,
    });
    expect(() => new Date(provenance.fetchedAt).toISOString()).not.toThrow();
  });

  it('builds the URL stem from the file class (Treble Bob -> TrebleBob)', async () => {
    const url = `${BASE}/CCCBR_TrebleBob6.html`;
    const { fn, calls } = fakeFetch({ [url]: file([row('1', 'Kent', 6, 'f', ['34', '-', '16', '-'])]) });
    await loadMethods('Treble Bob', Stage.MINOR, { fetch: fn, baseUrl: BASE });
    expect(calls).toEqual([url]);
  });

  it('rejects an unpublished (class, stage) with RangeError and does NOT fetch', async () => {
    const { fn, calls } = fakeFetch({});
    await expect(loadMethods('Surprise', Stage.TRIPLES, { fetch: fn, baseUrl: BASE }))
      .rejects.toThrow(RangeError);
    expect(calls).toEqual([]); // no dead fetch
  });

  it('throws CccbrLoadError on a non-2xx response', async () => {
    const { fn } = fakeFetch({}); // every URL 404s
    await expect(loadMethods('Surprise', Stage.MINOR, { fetch: fn, baseUrl: BASE }))
      .rejects.toBeInstanceOf(CccbrLoadError);
  });

  it('throws CccbrLoadError (with cause) when the fetch itself rejects', async () => {
    const boom = new Error('offline');
    const fn: FetchLike = async () => { throw boom; };
    const err = await loadMethods('Surprise', Stage.MINOR, { fetch: fn, baseUrl: BASE })
      .catch((e) => e);
    expect(err).toBeInstanceOf(CccbrLoadError);
    expect((err as CccbrLoadError).url).toBe(`${BASE}/CCCBR_Surprise6.html`);
    expect((err as CccbrLoadError).cause).toBe(boom);
  });
});

describe('cccbr-methods — loadStage', () => {
  it('fetches every class publishing the stage and merges them', async () => {
    const plainUrl = `${BASE}/CCCBR_Plain20.html`;
    const surpriseUrl = `${BASE}/CCCBR_Surprise20.html`;
    const { fn, calls } = fakeFetch({
      [plainUrl]: file([
        row('900', 'Plain Bob', 20, 'a', ['-', '10']),
        row('901', 'Double Court', 20, 'a', ['-', '12']),
      ]),
      [surpriseUrl]: file([row('902', 'Cambridge', 20, 'a', ['-', '10'])]),
    });

    const { library, provenance } = await loadStage(20, { fetch: fn, baseUrl: BASE });

    expect(calls.sort()).toEqual([plainUrl, surpriseUrl].sort()); // both classes, no more
    expect(library.size).toBe(3);
    expect(provenance).toMatchObject({
      stages: [20],
      fileClasses: ['Plain', 'Surprise'],
      methodCount: 3,
      upstreamGenerated: 'Mon 06 Jul 2026 17:49:53',
    });
  });

  it('rejects a stage no class publishes', async () => {
    const { fn } = fakeFetch({});
    // Stage 19 is not published by any modelled class.
    await expect(loadStage(19, { fetch: fn, baseUrl: BASE })).rejects.toThrow(RangeError);
  });

  it('propagates a CccbrLoadError if any class file fails', async () => {
    // Only provide Plain; Surprise20 will 404 -> the whole call rejects.
    const plainUrl = `${BASE}/CCCBR_Plain20.html`;
    const { fn } = fakeFetch({ [plainUrl]: file([row('900', 'Plain Bob', 20, 'a', ['-', '10'])]) });
    await expect(loadStage(20, { fetch: fn, baseUrl: BASE })).rejects.toBeInstanceOf(CccbrLoadError);
  });
});
