// Dynamic method-library loader — live CCCBR fetch for power users
// (Phase 4aa / ADR-0022).
//
// This is the package's **one opt-in network path**, deliberately kept OFF the
// zero-I/O root entry (ADR-0001) and shipped only on its own subpath export
// `ringing-lib-ts/cccbr-methods`. An app that never imports this module carries
// no fetch code and the core's "no network I/O" guarantee is untouched.
//
// Design (ADR-0022):
//   - Fetch **direct from CCCBR over HTTPS** — no project-hosted mirror.
//   - **Per (file-class, stage) is the primitive** (`loadMethods`): one CCCBR
//     file = one fetch (e.g. Surprise Minor = `CCCBR_Surprise6.html`). A
//     whole-stage convenience (`loadStage`) loops-and-merges a stage's classes.
//   - **Parse the raw Text client-side**, reusing the shared pure parser
//     (`./parse-text.ts`).
//   - **Tag results with provenance** (upstream "Generated on" marker + fetch
//     date) so the app can surface staleness and own the refresh decision.
//   - **Fail loud, degrade gracefully:** a network/HTTP failure throws a typed
//     `CccbrLoadError` (never silently swallowed); the app catches it and falls
//     back to the bundled `STANDARD_SET`. CORS support is CCCBR's to change, so
//     that fallback is load-bearing, not optional.

import { type Stage } from '../bell.js';
import { MethodLibrary, type MethodLibraryEntry } from '../method-library.js';
import {
  parseTextLibrary,
  extractUpstreamDate,
  type CccbrFileClass,
} from './parse-text.js';

export type { CccbrFileClass } from './parse-text.js';
export { parseTextLibrary, extractUpstreamDate } from './parse-text.js';

/** The CCCBR Methods Library Text endpoint. HTTPS — a browser blocks the http:// form as mixed content. */
export const DEFAULT_BASE_URL = 'https://methods.cccbr.org.uk/text';

interface ClassInfo {
  /** The URL stem (spaces removed): `Treble Bob` -> `TrebleBob`. */
  readonly stem: string;
  /** The stages CCCBR publishes for this class (from the library index). */
  readonly stages: readonly number[];
}

/**
 * File-class -> URL stem + published stages. Mirrors the authoring-time
 * `CLASS_STAGES` in `scripts/refresh-method-library.mjs`; Jump/Dynamic omitted
 * (extended notation). Shipped so an app can build a valid class×stage picker
 * and the loader can reject a (class, stage) that doesn't exist before fetching.
 */
const CLASS_INFO: Record<CccbrFileClass, ClassInfo> = {
  'Alliance': { stem: 'Alliance', stages: [3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 14, 16] },
  'Delight': { stem: 'Delight', stages: [6, 8, 10, 12, 14, 16] },
  'Hybrid': { stem: 'Hybrid', stages: [2, 3, 4, 5, 6, 8, 10, 12, 16] },
  'Plain': { stem: 'Plain', stages: [3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 18, 20, 22] },
  'Principle': { stem: 'Principle', stages: [2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 15, 17] },
  'Surprise': { stem: 'Surprise', stages: [6, 8, 9, 10, 11, 12, 14, 16, 18, 20] },
  'Treble Bob': { stem: 'TrebleBob', stages: [4, 6, 8, 10, 12, 14, 16] },
  'Treble Place': { stem: 'TreblePlace', stages: [3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 16] },
};

/** All eight fetchable CCCBR file classes — the values a picker offers. */
export const CCCBR_FILE_CLASSES = Object.keys(CLASS_INFO) as CccbrFileClass[];

/**
 * The class×stage availability map: which stages each file class publishes.
 * Ship this to a UI so it only ever offers (class, stage) pairs that exist.
 */
export const CCCBR_AVAILABILITY: Readonly<Record<CccbrFileClass, readonly number[]>> =
  Object.fromEntries(
    CCCBR_FILE_CLASSES.map((c) => [c, CLASS_INFO[c].stages]),
  ) as Record<CccbrFileClass, readonly number[]>;

/** The stages CCCBR publishes for a given file class (empty for an unknown class). */
export function stagesForClass(fileClass: CccbrFileClass): number[] {
  const info = CLASS_INFO[fileClass];
  return info ? [...info.stages] : [];
}

/** The file classes that publish a given stage (the classes `loadStage` will fetch). */
export function classesForStage(stage: number): CccbrFileClass[] {
  return CCCBR_FILE_CLASSES.filter((c) => CLASS_INFO[c].stages.includes(stage));
}

/** Whether CCCBR publishes a file at this (class, stage). */
export function isAvailable(fileClass: CccbrFileClass, stage: number): boolean {
  const info = CLASS_INFO[fileClass];
  return info != null && info.stages.includes(stage);
}

/** Where a loaded library came from and how current it is (ADR-0022). */
export interface LibraryProvenance {
  /** Always `'cccbr-text'` for this loader — a discriminator for future sources. */
  readonly source: 'cccbr-text';
  /**
   * The CCCBR "Generated by ... on <date>" marker (e.g. `'Mon 06 Jul 2026
   * 17:49:53'`), or `null` if the file carried none. The upstream freshness
   * signal — an app caches on it and offers a refresh when it moves.
   */
  readonly upstreamGenerated: string | null;
  /** ISO-8601 timestamp of when this fetch happened (client clock). */
  readonly fetchedAt: string;
  /** Stage(s) loaded. */
  readonly stages: number[];
  /** File class(es) loaded. */
  readonly fileClasses: CccbrFileClass[];
  /** Number of methods parsed. */
  readonly methodCount: number;
}

/** A `MethodLibrary` plus where its methods came from. */
export interface LoadedLibrary {
  readonly library: MethodLibrary;
  readonly provenance: LibraryProvenance;
}

/** A minimal fetch shape — the global `fetch` satisfies it, and a test/proxy can supply its own. */
export type FetchLike = (
  url: string,
) => Promise<{ ok: boolean; status: number; text(): Promise<string> }>;

export interface LoadOptions {
  /** Override the fetch implementation (a proxy fetch, or a test double). Defaults to the global `fetch`. */
  readonly fetch?: FetchLike;
  /** Override the base URL (a CORS proxy, a self-hosted mirror). Defaults to `DEFAULT_BASE_URL`. */
  readonly baseUrl?: string;
}

/**
 * Thrown when a CCCBR fetch fails (offline, CORS, DNS, or a non-2xx status).
 * The loader never swallows a failure — callers catch this and fall back to the
 * bundled `STANDARD_SET` (ADR-0022 / ADR-0014: loader = mechanism, app = policy).
 */
export class CccbrLoadError extends Error {
  readonly url: string;
  constructor(message: string, url: string, options?: { cause?: unknown }) {
    super(message, options);
    this.name = 'CccbrLoadError';
    this.url = url;
  }
}

function resolveFetch(opts: LoadOptions): FetchLike {
  if (opts.fetch) return opts.fetch;
  const g = (globalThis as { fetch?: FetchLike }).fetch;
  if (!g) {
    throw new Error(
      'No global fetch available; pass options.fetch (Node < 18 or a non-fetch environment).',
    );
  }
  return g;
}

/**
 * Load one CCCBR file — all methods of one **file class** at one **stage**.
 * The headline primitive: one file, one fetch, one parse, no over-fetching
 * (the motivating case is a ringer preparing a peal of one new method — they
 * want that class at that stage, e.g. `loadMethods('Surprise', Stage.MINOR)`).
 *
 * @throws {RangeError}     if CCCBR publishes no file at this (class, stage) — no fetch is attempted.
 * @throws {CccbrLoadError} on any network failure or non-2xx response.
 */
export async function loadMethods(
  fileClass: CccbrFileClass,
  stage: Stage,
  opts: LoadOptions = {},
): Promise<LoadedLibrary> {
  const info = CLASS_INFO[fileClass];
  if (!info) throw new RangeError(`Unknown CCCBR file class: ${String(fileClass)}`);
  if (!info.stages.includes(stage)) {
    throw new RangeError(
      `CCCBR publishes no ${fileClass} at stage ${stage} ` +
        `(available: ${info.stages.join(', ')}).`,
    );
  }

  const base = opts.baseUrl ?? DEFAULT_BASE_URL;
  const url = `${base}/CCCBR_${info.stem}${stage}.html`;
  const doFetch = resolveFetch(opts);

  let res: { ok: boolean; status: number; text(): Promise<string> };
  try {
    res = await doFetch(url);
  } catch (cause) {
    throw new CccbrLoadError(`Network error fetching ${url}`, url, { cause });
  }
  if (!res.ok) {
    throw new CccbrLoadError(`GET ${url} returned HTTP ${res.status}`, url);
  }

  const raw = await res.text();
  const entries = parseTextLibrary(raw, { fileClass, stage });
  const provenance: LibraryProvenance = {
    source: 'cccbr-text',
    upstreamGenerated: extractUpstreamDate(raw),
    fetchedAt: new Date().toISOString(),
    stages: [stage],
    fileClasses: [fileClass],
    methodCount: entries.length,
  };
  return { library: new MethodLibrary(entries), provenance };
}

/**
 * Load **every method at one stage** — the whole-stage convenience. Fetches all
 * the file classes that publish `stage` (up to eight files) and merges them.
 * Heavier than {@link loadMethods} by design (a large stage is several MB of
 * Text); reach for it only when a full stage is genuinely wanted, not to grab
 * one method. If any class file fails, the whole call rejects with the first
 * `CccbrLoadError` (so the app falls back cleanly rather than getting a partial).
 *
 * @throws {RangeError}     if no CCCBR class publishes `stage`.
 * @throws {CccbrLoadError} if any of the underlying fetches fails.
 */
export async function loadStage(stage: Stage, opts: LoadOptions = {}): Promise<LoadedLibrary> {
  const classes = classesForStage(stage);
  if (classes.length === 0) {
    throw new RangeError(`No CCCBR classes publish stage ${stage}.`);
  }
  const loaded = await Promise.all(classes.map((c) => loadMethods(c, stage, opts)));

  const entries: MethodLibraryEntry[] = loaded.flatMap((l) => [...l.library]);
  const upstreamGenerated =
    loaded.map((l) => l.provenance.upstreamGenerated).find((d) => d != null) ?? null;

  const provenance: LibraryProvenance = {
    source: 'cccbr-text',
    upstreamGenerated,
    fetchedAt: new Date().toISOString(),
    stages: [stage],
    fileClasses: classes,
    methodCount: entries.length,
  };
  return { library: new MethodLibrary(entries), provenance };
}
