import { type MethodLibraryEntry } from '../method-library.js';
import data from './method-library/standard-set.json' with { type: 'json' };

/**
 * The always-bundled **standard set** — a few dozen real methods that cover the
 * overwhelming majority of what is rung — ready to drop straight into a
 * `MethodLibrary` (ADR-0015, ADR-0019).
 *
 * ```ts
 * import { MethodLibrary } from 'ringing-lib-ts';
 * import { STANDARD_SET } from 'ringing-lib-ts/data/standard-set';
 * const lib = new MethodLibrary(STANDARD_SET);
 * ```
 *
 * This is deliberately a **separate subpath export**, not part of the main
 * entry point: apps that don't want the ~7 KB of bundled method data simply
 * never import it, and it tree-shakes away (ADR-0019). It is also distinct from
 * `STANDARD_METHODS` (the small hand-verified *truth corpus*, exported from the
 * root): this set is bulk application data resolved at build time from
 * `standard-set-seed.json` against the CCCBR snapshot — no notation is hand-typed
 * (ADR-0015).
 *
 * The underlying JSON is generated by `npm run data:refresh`; every entry carries
 * the lean field set (`id`, `name`, `stage`, `classification`, `notation`, a
 * lead-head code or row, `symmetry`, `little`).
 */
export const STANDARD_SET: MethodLibraryEntry[] = data as unknown as MethodLibraryEntry[];

export default STANDARD_SET;
